DjangoLvlFive/DjangoLvlFive/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from FifthApp import views


urlpatterns = [
    path('', include('FifthApp.urls')),
    path('admin/', admin.site.urls)
    # It would be best to put the logout button here so that a user could log out of the whole project
    # instead of just one applicaiton

]

DjangoLvlFive/FifthApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from FifthApp import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('other/', views.other, name='other')
]

DjangoLvlFive/FifthApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)# Means that this field is required to be filled
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        # Built-in attribute
        # diango.contrib.auth.models.User
        return self.user.username



# This new model makes an extension on the pre existing models

DjangoLvlFive/FifthApp/forms.py
from django import forms
from django.contrib.auth.models import User
from FifthApp.models import UserProfileInfo

# Always put form after otherwise the framework will get confused
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username', 'email', 'password')# Could ad fist and last name if you want to


class UserProfileInfoForm(forms.ModelForm):


    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

DjangoLvlFive/FifthApp/views.py
import django.urls.exceptions
from django.shortcuts import render
from FifthApp.forms import UserForm, UserProfileInfoForm

# For Login Page
from django.urls import reverse  # do not use django.core.urls
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def home(request):
    return render(request, 'home.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('basic_app:home'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login an failed")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("Invalid Login details")
    return render(request, 'user_login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('basic_app:home'))


def register(request):
    registered = False  # This is saying that the user is not registered
    if request.method == 'POST':  # When request is equal to POST then we take the information
        user_form = UserForm(data=request.POST)  # Get information from the user form
        profile_form = UserProfileInfoForm(
            data=request.POST)  # Gets information from the profile form(Make sure the name is unique)
        if user_form.is_valid() and profile_form.is_valid():  # This checks that both forms are valid

            user = user_form.save()  # Saves information  directly to the database
            user.set_password(user.password)  # Hashes the password
            user.save()  # This saves th echages to the database

            profile = profile_form.save(
                commit=False)  # Directly saves to the database. Don't commit to the database yet otherwise we may get
            # collision errors
            profile.user = user  # Sets up a one-to-one relationship

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()  # Saves the model
            registered = True  # The user is now registered
        else:
            print(user_form.errors, profile_form.errors)

    else:  # This mean the request was actually a http request
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'register.html',
                  context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def other(request):
    return render(request, 'other.html')

DjangoLvlFive/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Level Five</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static '/css/mystyle.css' %}"/>
</head>
<body>
    <nav class="navbar navbar-expand-lg" style="background-color: #c8940c;">
        <ul class="nav navbar-nav">
            <li class="nav-item ml-4"><a id="logo" class="navbar-brand" href="{%url 'basic_app:home'%}"><img src="{% static 'images/logo.png'%}" alt="Your Logo" style="width:100px; height: 40px;"></a></li>
            <li class="nav-item ml-4"><a class="navbar-link" href="{%url 'admin:index'%}">Admin</a></li>
            <li class="nav-item ml-4"><a class="navbar-link" href="{%url 'basic_app:register'%}">Registeration</a></li>
            <li class="nav-item ml-4"><a class="navbar-link" href="{%url 'basic_app:other'%}">Other</a></li>
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'basic_app:logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'basic_app:user_login'%}">Login</a></li>
            {% endif %}
        </ul>

    </nav>}
    <div class="container">
        {% block body_block %}
        <!-- Anthing outside of this will be inherited it you extend! -->
        {% endblock %}
    </div>
</body>
</html>

DjangoLvlFive/templates/error.html
{% extends 'base.html' %}
{% block body_block%}

<p>Something went Wrong</p>

{% endblock%}

DjangoLvlFive/templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block %}

        <div class="container">
            <div class="jumbotron">
                <h1>This is my website: DjangoLvlFive(FifthApp)</h1>
                <a href="{% url 'basic_app:other'%}">Other Page</a>
                <br>
                <a href="{% url 'admin:index' %}">Admin Page</a>
                <br>
            </div>
        </div>

    {% endblock %}

DjangoLvlFive/templates/other.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block %}
        <h1>This is the Other page</h1>

    {% endblock %}

DjangoLvlFive/templates/register.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block %}
        <h1>Registeration Page</h1>
        <div class="jumbotron" style="background-color: #E4E1DC;">
            {% if registered %}
                <h1>Thanks for registering</h1>
            {% else %}

               <h3>Fill in the form:</h3>

                <form method="post" enctype="multipart/form-data">
                    <!-- enctype is for forms the request  extra media-->
                    {% csrf_token %}
                    {{ user_form.as_p}}
                    {{ profile_form.as_p}}
                    <input type="submit" name="" value="Register">
            {% endif %}
        </div>
    {% endblock %}

DjangoLvlFive/templates/user_login.html
{% extends 'base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login'%}" method="POST">
        {% csrf_token %}
        <label for="username" >Username:</label>
        <input type="text" name="username" placeholder="Enter Username" >

        <label for="password" >Password:</label>
        <input type="text" name="password" placeholder="Enter Password" >

        <input type="submit" name="" value="Login">
    </form>


</div>

{% endblock %}